### ISSUE TITLE
[Feature] 将所有的备份规则上传到webdav

### ISSUE THREAD

**Issue by Goojoe** [XayahSuSuSu/Android-DataBackup#176]
我理想的备份软件是这样的，将所有备份的规则写入yaml/conf
比如说：
- 选择应用的数据
- 黑名单
- 仅备份APK 
- 文件目录 DCIM Download
- 通讯录等等
将这些全都写入配置文件，就可以一键备份 而不是每次备份三个选项都要手动点，这还是太麻烦了

另外问下备份完成后就/sdcard/DataBackup打包成zip有计划吗，我之前好像说过，这个真的刚需，手动去打包又多了一个步骤(我真不想自己打包重命名日期) 打包名遵循：DataBackup_yyyy-mm-dd_hh-mm-ss

全自动的好处就是我备份完后直接传输到电脑一气呵成，每次重复点来点去很费心

补充yaml：
```
app:
    backup: true
    appAll(备份APK和数据):
        - com.tencent.mm
    onlyApk:
        - com.alipay
    appBlackList:
        - ...
data:
    backup: true
    data:
        - /data/data/com.tencent.mm

addressBook-and-callHistory-and-SMS:
    backup: true

after-archive
    backup: true
    time: yyyy-mm-dd_hh-mm-ss
```
