### ISSUE TITLE
reproducible build for 2.0.6_1 failed

### ISSUE THREAD

**Issue by IzzySoft** [XayahSuSuSu/Android-DataBackup#337]
Just a note @XayahSuSuSu: reproducible build for 2.0.6_1 failed today, and I was not able to repair it (some minor differences in `baseline.prof`). I thought it might be a "flaky build" (i.e. a non-deterministic one), so I tried to run it in a loop to see whether it would produce different variants – but nope. The `_1` at the tag/release name seems to suggest you had some troubles with this release as well, could that be? Was the APK at that release built from a clean tree (i.e. without local changes, or artifacts remaining from previous builds) at the commit the tag points to (febb809)?

Just for reference, this is the APK diff:

```diff
  -rw-r--r--  0.0 unx       46 b-       48 defN 1981-01-01 01:01:02 b8ff6554 META-INF/version-control-info.textproto
- -rw-r--r--  0.0 unx     7932 b-     7932 stor 1981-01-01 01:01:02 590590b1 assets/dexopt/baseline.prof
+ -rw-r--r--  0.0 unx     7933 b-     7933 stor 1981-01-01 01:01:02 bd6c659c assets/dexopt/baseline.prof
  -rw-r--r--  0.0 unx     1045 b-     1045 stor 1981-01-01 01:01:02 b9f03b35 assets/dexopt/baseline.profm
```

and this the baseline diff:

```diff
   num_type_ids=3673
-  hot_method_region_size=41960
+  hot_method_region_size=41964
   dex_checksum=0x2ce81ee0
   num_method_ids=65165
 dex_data_header 1
@@ -16,7 +16,7 @@
   dex_checksum=0xa0926c22
   num_method_ids=18234
 dex_data 0
-  num_hot_method_ids=10490
+  num_hot_method_ids=10491
   num_type_ids=3673
   method_id=0
   num_inline_caches=0
@@ -2028,6 +2028,8 @@
   num_inline_caches=0
   method_id=1784
   num_inline_caches=0
+  method_id=1810
+  num_inline_caches=0
   method_id=1811
```

What irritates me is the last segment, which looks like something in your APK but entirely missing from mine. But only in the baseline, no other diffs in the APK.

**Comment by XayahSuSuSu** [comment]
> The _1 at the tag/release name seems to suggest you had some troubles with this release as well, could that be?

It's just a fix for known issues on 2.0.6, it may not be.

> Was the APK at that release built from a clean tree (i.e. without local changes, or artifacts remaining from previous builds) at the commit the tag points to (https://github.com/XayahSuSuSu/Android-DataBackup/commit/febb8097e22f6204ec8216adad9c9e87b20de7b7)?

Yes, it's a clean [build](https://github.com/XayahSuSuSu/Android-DataBackup/actions/runs/12620046744).

It's weird I don't think I've modifed anything related to this baseline...

Maybe I can trigger a new build to see if it's the same as released apk.

**Comment by IzzySoft** [comment]
> It's just a fix for known issues on 2.0.6, it may not be.

OK, I just wondered as there is no 2.0.6 :man_shrugging:

> Maybe I can trigger a new build to see if it's the same as released apk.

Would be good to know, yeah – to be prepared for the next release at least. Thanks!

**Comment by XayahSuSuSu** [comment]
I checked two builds([re-triggered](https://github.com/XayahSuSuSu/Android-DataBackup/actions/runs/12636498301), [released](https://github.com/XayahSuSuSu/Android-DataBackup/actions/runs/12620046744)) with diffoscope, and it's totally the same.

![image](https://github.com/user-attachments/assets/0b5c3ece-8fc1-4783-b9ba-532b535fd56c)

Besides, it seems that baseline is the same between [DataBackup-2.0.6_1-arm64-v8a-foss-release.apk](https://github.com/XayahSuSuSu/Android-DataBackup/actions/runs/12636498301) and [com.xayah.databackup.foss_3501134.apk](https://gitlab.com/fdroid/fdroiddata/-/jobs/8773767553).

**Comment by IzzySoft** [comment]
Well, it's different here (I can send you a diffoscope as well if you want). Maybe comparing build recipes?

```yaml
  - tag: 2.0.6_1
    apks:
      - apk_pattern: DataBackup-.*armeabi-v7a-foss-release\.apk
        apk_url: https://github.com/XayahSuSuSu/Android-DataBackup/releases/download/2.0.6_1/DataBackup-2.0.6_1-armeabi-v7a-foss-release.apk
        build:
          - cd source
          - chmod +x gradlew
          - sed -r '/signingConfigs.getByName/d' -i build-logic/convention/src/main/kotlin/ApplicationCommonConventionPlugin.kt
          - PROF_FILE=app/build/intermediates/binary_art_profile/armeabi-v7aFossRelease/compileArmeabi-v7aFossReleaseArtProfile/baseline.prof
          - PROF_SHA1=cf1cb00e3e4cb5b28924ecd1728604b22b83bb41
          - for _ in {1..10}; do
          - ./gradlew clean assembleArmeabi-v7aFossRelease --no-build-cache --no-configuration-cache --no-daemon
          - test -f "${PROF_FILE}"
          - if [ "$( sha1sum "$PROF_FILE" | cut -d' ' -f1 )" = "$PROF_SHA1" ]; then
          - break
          - fi
          - done
          - mv app/build/outputs/apk/armeabi-v7aFoss/release/DataBackup-*-armeabi-v7a-foss-release.apk /outputs/unsigned.apk
        build_home_dir: /build
        build_repo_dir: /build/repo
        build_user: build
        provisioning:
          android_home: /opt/sdk
          build_tools:
          cmake:
          cmdline_tools:
            version: '12.0'
            url: https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
            sha256: 2d2d50857e4eb553af5a6dc3ad507a17adf43d115264b1afc116f95c92e5e258
          extra_packages: []
          image: debian:bookworm-slim
          jdk: openjdk-17-jdk-headless
          ndk:
          platform:
          platform_tools:
          tools:
          verify_gradle_wrapper: true
```

The relevant part is basically:

```yaml
- ./gradlew clean assembleArmeabi-v7aFossRelease --no-build-cache --no-configuration-cache --no-daemon
```

The loop around is just to rule out "flaky builds" (non-deterministic ones: different results with each build; 1 out of 5..10 matches "upstream" usually, to our experience).

And the important points to check: OpenJDK-17 here, on Debian bookworm. You build with the zulu JDK, which usually is relatively close to OpenJDK (most successful RB projects use temurin, if I counted that correctly). On Ubuntu 24.04, which should be pretty close to bookworm. We could try using the `ubuntu:noble` image instead and see if that makes a difference – but we cannot use zulu as that's not in the standard repos.

What else could it be: some specific bugs in the tooling – like the "number of cores" bug. The diff doesn't look like that, but we could try to match the CPU count: Github actions use 4 cores IIRC.

Looking at `META-INF/version-control-info.textproto` I'm confused, though: `generate_error_reason: NO_SUPPORTED_VCS_FOUND` usually means it was not built from within a git repo (but e.g. from a tarball). But our APK shows the same, and I know for 100% that was build from within the cloned repo. Strange, very strange. Well, we can be pretty sure having built from the same commit: your action clearly states the commit from the tag. It's just the baseline that differs, nothing else. The only corresponding bug I know for this is supposed to have been fixed with AGP 8.1.0.

So unless you see something wrong with `./gradlew assembleArmeabi-v7aFossRelease`, I could try the following in this order:

* try building on `ubuntu:noble`
* limiting CPU cores to 4

What you could try is copying the workflow and try a build with `temurin` to see if that differs from the one with `zulu` (you'd do me a favor with that as well, as I'm still unsure concerning `zulu` if it's really that different).

What do you think?
